version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: agri-logistics-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agri_logistics
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
